name: Intro

on:
  workflow_dispatch:
    inputs:
      name:
        type: text
        description: "Your name:"
        required: true
        default: "Fred"

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
    - name: Hello world
      id: greeting-step
      run: |
        GREETING="Hello, ${{github.event.inputs.name}}"
        echo "::set-output name=greeting::${GREETING}"

    - run: echo "${steps.greeting-step.outputs.greeting}"
