name: Intro

on:
  workflow_dispatch:
    inputs:
      name:
        type: text
        description: "Your name:"
        required: true
        default: "Fred"
      shoutout:
        type: boolean
        description: "Should I shout this?"
        required: true
        default: "true"
      language:
        type: choice
        description: "Choose a language:"
        required: true
        options:
        - english
        - french

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      greeting: ${{steps.greeting-step.outputs.greeting}}
      shoutout: ${{steps.shoutout-step.outputs.shoutout}}

    steps:
    - uses: actions/checkout@v3

    - id: language-step
      run: |
        PREFIX=$(jq -Mr '.${{github.event.inputs.language}}' languages.json)
        echo "::set-output name=prefix::${PREFIX}"

    - name: Hello world
      id: greeting-step
      run: |
        GREETING="${{steps.language-step.outputs.prefix}}, ${{github.event.inputs.name}}"
        echo "::set-output name=greeting::${GREETING}"

    - id: shoutout-step
      run: |
        if [ "${{github.event.inputs.shoutout}}" == "true" ]; then SHOUTOUT="!"; else SHOUTOUT=""; fi
        echo "::set-output name=shoutout::${SHOUTOUT}"

  greeting:
    needs: config
    runs-on: ubuntu-latest

    steps:
    - run: echo "${{needs.config.outputs.greeting}}${{needs.config.outputs.shoutout}}"
