name: Intro

on:
  workflow_dispatch:
    inputs:
      name:
        type: text
        description: "Your name:"
        required: true
        default: "Fred"

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
    - name: Hello world
      run: echo "Hello, ${{github.event.inputs.name}}"
